// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmw97-gCFGrVcmrD4X4BCcYQtz9TOYaEM',
    appId: '1:797221656485:web:72d6bdc8d54b53c26d7a4c',
    messagingSenderId: '797221656485',
    projectId: 'digigold-app',
    authDomain: 'digigold-app.firebaseapp.com',
    storageBucket: 'digigold-app.firebasestorage.app',
    measurementId: 'G-29MS3R2CHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj0aXoVGRKQwkkVdCrDzUD1z4yAI7I7N4',
    appId: '1:797221656485:android:95db6ab89d441d576d7a4c',
    messagingSenderId: '797221656485',
    projectId: 'digigold-app',
    storageBucket: 'digigold-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKAgt4fm03-LLTApKilcMy7RskYqC0W5A',
    appId: '1:797221656485:ios:11945a0d20c303fd6d7a4c',
    messagingSenderId: '797221656485',
    projectId: 'digigold-app',
    storageBucket: 'digigold-app.firebasestorage.app',
    iosBundleId: 'com.example.trj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKAgt4fm03-LLTApKilcMy7RskYqC0W5A',
    appId: '1:797221656485:ios:11945a0d20c303fd6d7a4c',
    messagingSenderId: '797221656485',
    projectId: 'digigold-app',
    storageBucket: 'digigold-app.firebasestorage.app',
    iosBundleId: 'com.example.trj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmw97-gCFGrVcmrD4X4BCcYQtz9TOYaEM',
    appId: '1:797221656485:web:6b9a29488574e7e46d7a4c',
    messagingSenderId: '797221656485',
    projectId: 'digigold-app',
    authDomain: 'digigold-app.firebaseapp.com',
    storageBucket: 'digigold-app.firebasestorage.app',
    measurementId: 'G-H5VFH832ER',
  );
}
